spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/tracelm
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

llm:
  default-provider: openai

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-1.5-flash